services:
  - type: web
    name: specialwash-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.wsgi:app
    postDeployCommand: |
      python -m flask db upgrade
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: src/app.py
      - key: DATABASE_URL
        sync: false          # la pones tú en el panel (Internal URL de tu Postgres)
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: TZ
        value: Europe/Madrid
      # CORS: el backend leerá esta variable y la aplicará
      - key: CORS_ORIGINS
        fromService:
          type: static_site
          name: specialwash-frontend
          property: url

  - type: static_site
    name: specialwash-frontend
    env: static
    region: frankfurt
    buildCommand: |
      cd frontend
      yarn install --frozen-lockfile
      yarn build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: specialwash-backend
          property: url
