databases:
  - name: specialwash-db
    plan: free

services:
  - name: specialwash-api
    type: web
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.app:app
    postDeployCommand: FLASK_APP=src/app.py PYTHONPATH=src flask db upgrade
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: PYTHONPATH
        value: src
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_APP_KEY
        generateValue: true
      # ⚠️ tras desplegar el frontend, actualiza este valor con la URL real del static site:
      - key: FRONTEND_ORIGIN
        value: https://<frontend-domain>.onrender.com

  - name: specialwash-frontend
    type: static
    region: oregon
    buildCommand: npm ci && npm run build
    # Cambia a 'build' si tu webpack genera 'build' en lugar de 'dist'
    staticPublishPath: dist
    envVars:
      # ⚠️ tras saber la URL de la API, actualiza esto con la URL real:
      - key: REACT_APP_BACKEND_URL
        value: https://<api-domain>.onrender.com/api
