services:
  # Backend Flask
  - type: web
    name: specialwash-backend
    env: python
    rootDir: .
    buildCommand: bash ./render_build.sh         # << construye front y back
    startCommand: gunicorn src.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: FRONTEND_ORIGIN
        value: https://specialwash-frontend.onrender.com
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true

  # Frontend React (si lo separas como Static Site)
  - type: static
    name: specialwash-frontend
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: public                    # << aquí va "public", NO "dist"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://specialwash-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
