services:
  - type: web
    name: specialwash-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    # ⬇️ TEMPORAL: fuerza "olvidar" la revisión antigua y aplicar las nuevas
    startCommand: flask --app src.app db stamp base && flask --app src.app db upgrade && exec gunicorn -w 2 -k gthread --threads 8 --timeout 120 -b 0.0.0.0:$PORT src.app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ENV
        value: production
      - key: JWT_SECRET_KEY
        value: change-me-in-prod
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: FRONTEND_ORIGIN
        value: https://specialwash-frontend.onrender.com

  - type: postgres
    name: specialwash-db
    plan: free
