services:
  - type: web
    name: specialwash1
    env: python
    plan: free
    branch: main
    autoDeploy: true

    buildCommand: |
      pip install -r requirements.txt
      if [ -f package.json ]; then
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
        npm run build
      fi

    startCommand: >
      gunicorn -w 4 -k gthread -b 0.0.0.0:$PORT src.app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      # Descomenta y pon tu valor si lo usas en Flask
      # - key: SECRET_KEY
      #   value: "cambia-esto-por-tu-clave"
