services:
  # =========================
  # Backend Flask (Web Service)
  # =========================
  - type: web
    name: specialwash-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app src.app db upgrade && gunicorn -w 2 -k gthread --threads 8 --timeout 120 -b 0.0.0.0:$PORT src.app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ENV
        value: production
      - key: JWT_SECRET_KEY
        value: change-me-in-prod
      - key: DATABASE_URL
        # Render genera automáticamente esta URL si añades el servicio PostgreSQL
        value: ""
      - key: FRONTEND_ORIGIN
        value: https://specialwash-frontend.onrender.com

  # =========================
  # Base de datos PostgreSQL
  # =========================
  - type: postgres
    name: specialwash-db
    plan: free

  # =========================
  # Frontend React (Static Site)
  # =========================
  - type: static
    name: specialwash-frontend
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://specialwash-backend.onrender.com
