databases:
  - name: specialwash-db
    plan: free

services:
  - name: specialwash
    type: web
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      npm ci
      npm run build
    preDeployCommand: FLASK_APP=src/app.py PYTHONPATH=src flask db upgrade
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: PYTHONPATH
        value: src
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_APP_KEY
        generateValue: true
      # El frontend hablará con la API en el mismo origen:
      - key: REACT_APP_BACKEND_URL
        value: /api
