databases:
  - name: specialwash-db
    plan: free

services:
  # API Flask
  - name: specialwash-api
    type: web
    runtime: python            # en vez de env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    preDeployCommand: FLASK_APP=src/app.py PYTHONPATH=src flask db upgrade
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString
      - key: PYTHONPATH
        value: src
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_APP_KEY
        generateValue: true
      # ⚠️ tras desplegar el frontend, poner aquí la URL real del sitio estático
      - key: FRONTEND_ORIGIN
        value: https://<frontend-domain>.onrender.com

  # Frontend estático (Webpack)
  - name: specialwash-frontend
    type: web
    runtime: static            # static site → type:web + runtime:static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist    # cambia a 'build' si tu bundle sale en build/
    envVars:
      # ⚠️ tras desplegar la API, poner aquí la URL pública de la API
      - key: REACT_APP_BACKEND_URL
        value: https://<api-domain>.onrender.com/api
