services:
  - type: web
    name: specialwash-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r src/requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.wsgi:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGIN
        fromService:
          type: static_site
          name: specialwash-frontend
          property: url
      - key: FLASK_ENV
        value: production

  - type: static_site
    name: specialwash-frontend
    env: static
    region: frankfurt
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: specialwash-backend
          property: url
