"""init schema

Revision ID: 96e9fd48fc07
Revises: 44705f6cc9f6
Create Date: 2025-08-28 15:27:22.307287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96e9fd48fc07'
down_revision = '44705f6cc9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('maquinaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('numero_serie', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('ultima_revision', sa.Date(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('registro_entrada_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=120), nullable=True),
    sa.Column('precio_bruto_sin_iva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precio_sin_iva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precio_con_iva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_salida_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    op.drop_table('hoteltheme')
    op.drop_table('housekeeper')
    op.drop_table('housekeepertask')
    op.drop_table('hoteles')
    op.drop_table('theme')
    op.drop_table('room')
    op.drop_table('maintenancetask')
    op.drop_table('user')
    op.drop_table('branches')
    op.drop_table('maintenance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('maintenance_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='maintenance_branch_id_fkey'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], name='maintenance_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenance_pkey'),
    sa.UniqueConstraint('email', name='maintenance_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('branches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('branches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('longitud', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitud', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], name='branches_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='branches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('theme', name='user_theme_key')
    )
    op.create_table('maintenancetask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('housekeeper_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finalizado_por', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='maintenancetask_category_id_fkey'),
    sa.ForeignKeyConstraint(['housekeeper_id'], ['housekeeper.id'], name='maintenancetask_housekeeper_id_fkey'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], name='maintenancetask_maintenance_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='maintenancetask_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenancetask_pkey')
    )
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('room_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='room_branch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('theme',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('theme_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='theme_pkey'),
    sa.UniqueConstraint('nombre', name='theme_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('hoteles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hoteles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hoteles_pkey'),
    sa.UniqueConstraint('email', name='hoteles_email_key'),
    sa.UniqueConstraint('nombre', name='hoteles_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('housekeepertask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('assignment_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('submission_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('id_room', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_housekeeper', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nota_housekeeper', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_housekeeper'], ['housekeeper.id'], name='housekeepertask_id_housekeeper_fkey'),
    sa.ForeignKeyConstraint(['id_room'], ['room.id'], name='housekeepertask_id_room_fkey'),
    sa.PrimaryKeyConstraint('id', name='housekeepertask_pkey')
    )
    op.create_table('housekeeper',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('id_branche', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_branche'], ['branches.id'], name='housekeeper_id_branche_fkey'),
    sa.PrimaryKeyConstraint('id', name='housekeeper_pkey'),
    sa.UniqueConstraint('email', name='housekeeper_email_key'),
    sa.UniqueConstraint('nombre', name='housekeeper_nombre_key')
    )
    op.create_table('hoteltheme',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_hoteles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_theme', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_hoteles'], ['hoteles.id'], name='hoteltheme_id_hoteles_fkey'),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], name='hoteltheme_id_theme_fkey'),
    sa.PrimaryKeyConstraint('id', name='hoteltheme_pkey')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.drop_table('registro_salida_producto')
    op.drop_table('registro_entrada_producto')
    op.drop_table('maquinaria')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('producto')
    # ### end Alembic commands ###
