"""init

Revision ID: b3362f54a9e0
Revises: 96e9fd48fc07
Create Date: 2025-09-02 15:59:43.179625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3362f54a9e0'
down_revision = '96e9fd48fc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('numero_albaran', sa.String(length=120), nullable=True),
    sa.Column('precio_sin_iva', sa.Float(), nullable=True),
    sa.Column('porcentaje_iva', sa.Float(), nullable=True),
    sa.Column('valor_iva', sa.Float(), nullable=True),
    sa.Column('precio_con_iva', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('registro_salida_producto')
    op.drop_table('usuario')
    op.drop_table('registro_entrada_producto')
    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')
        batch_op.drop_column('modelo')
        batch_op.drop_column('marca')
        batch_op.drop_column('numero_serie')
        batch_op.drop_column('fecha_compra')
        batch_op.drop_column('ultima_revision')
        batch_op.drop_column('estado')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('contacto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('maquinaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ultima_revision', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('fecha_compra', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('numero_serie', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('proveedor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'proveedor', ['proveedor_id'], ['id'])
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    op.create_table('registro_entrada_producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('fecha_entrada', sa.DATETIME(), nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(length=20), nullable=True),
    sa.Column('numero_documento', sa.VARCHAR(length=120), nullable=True),
    sa.Column('precio_bruto_sin_iva', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('descuento_porcentaje', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('precio_sin_iva', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('iva_porcentaje', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('precio_con_iva', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('rol', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registro_salida_producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('fecha_salida', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('salida')
    op.drop_table('entrada')
    op.drop_table('user')
    # ### end Alembic commands ###
